# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mnemonics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(default=19, verbose_name='幾式')),
                ('num2', models.IntegerField(default=1, verbose_name='第幾式')),
                ('num3', models.IntegerField(default=0, verbose_name='第幾動')),
                ('data', models.CharField(max_length=200, verbose_name='口訣')),
            ],
            options={
                'verbose_name': '口訣',
                'verbose_name_plural': '口訣',
            },
        ),
    ]
